# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e35670eba57e118ba1faf557263384400d9af3a33b9df156892c22525577f339f593d4dd19354c1357ca49d1231be094e976d5c08ef5872d2f231ea4ae72ee7

test:
  secret_key_base: 5d777d04332a347edbc4119a4cd06ab94b3457b157e274ff4e9931a60b8febb9acbb7d1c90d207e1e8f6d1641cda46bab55983f5beef124e3e5b97d112b57a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
